// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCu4_PNmEQ1PL5w-U3tBV3h6B3r2kY1rCo',
    appId: '1:101994278872:web:6e5bf5177d61ff9e754cad',
    messagingSenderId: '101994278872',
    projectId: 'esp82266-31379',
    authDomain: 'esp82266-31379.firebaseapp.com',
    databaseURL: 'https://esp82266-31379-default-rtdb.firebaseio.com',
    storageBucket: 'esp82266-31379.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXFshRhZDeI1No2o6Z02qgRYdaLyShPKY',
    appId: '1:101994278872:android:937732fbee7c142a754cad',
    messagingSenderId: '101994278872',
    projectId: 'esp82266-31379',
    databaseURL: 'https://esp82266-31379-default-rtdb.firebaseio.com',
    storageBucket: 'esp82266-31379.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3u2b88dx7I1kjkax4jmLhESGCDQID6IU',
    appId: '1:101994278872:ios:bbaf518d3c54cf31754cad',
    messagingSenderId: '101994278872',
    projectId: 'esp82266-31379',
    databaseURL: 'https://esp82266-31379-default-rtdb.firebaseio.com',
    storageBucket: 'esp82266-31379.appspot.com',
    iosBundleId: 'com.jnc.zypherion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3u2b88dx7I1kjkax4jmLhESGCDQID6IU',
    appId: '1:101994278872:ios:bbaf518d3c54cf31754cad',
    messagingSenderId: '101994278872',
    projectId: 'esp82266-31379',
    databaseURL: 'https://esp82266-31379-default-rtdb.firebaseio.com',
    storageBucket: 'esp82266-31379.appspot.com',
    iosBundleId: 'com.jnc.zypherion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCu4_PNmEQ1PL5w-U3tBV3h6B3r2kY1rCo',
    appId: '1:101994278872:web:424cec2f39160e6f754cad',
    messagingSenderId: '101994278872',
    projectId: 'esp82266-31379',
    authDomain: 'esp82266-31379.firebaseapp.com',
    databaseURL: 'https://esp82266-31379-default-rtdb.firebaseio.com',
    storageBucket: 'esp82266-31379.appspot.com',
  );

}